# Generated by Django 5.2.7 on 2025-10-10 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personnel',
            new_name='Agent',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_personnel',
            new_name='assigned_agent',
        ),
    ]
