# Generated by Django 5.2.7 on 2025-10-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_requester_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assessing', 'Assessing'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='pending', max_length=10),
        ),
    ]
