# Generated by Django 5.2.7 on 2025-11-19 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_department_agent_department_tickettype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type', to='tickets.department'),
        ),
    ]
