# Generated by Django 5.2.7 on 2025-11-22 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='tickets.agent'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='tickets.tickettype'),
        ),
    ]
