# Generated by Django 5.2.7 on 2025-11-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_specialization_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='department',
        ),
    ]
