# Generated by Django 5.2.7 on 2025-11-22 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_remove_tickettype_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='tickets.department'),
        ),
    ]
