# Generated by Django 5.2.7 on 2025-11-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_agent_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
