# Generated by Django 5.2.7 on 2025-11-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_ticket_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
